### ISSUE TITLE
Storage allocation issue (caused by mods that add wares)

### ISSUE THREAD

**Issue by tizubythefizo** [h2odragon/tradebeacons#1]
Hey there,

So in the EgoSoft discord we discovered an issue with the way the game's code allocates station storage space when mods add wares.

The gist is that, mods that add wares, particularly ones that require heavy goods (such as scanning arrays) throw off the balance of allocated goods to the point that things like the allocated space for hull parts becomes less than it takes to build some ships (making them effectively impossible to build). This gets compounded when combining mods that add wares (like VRO, extra weapons, etc...).

This is most pronounced at the split wharf (they have low storage there) and paranid wharfs.

The recommended workaround we came up with is to diversify the goods required to make them by adding goods that end up critically short on allocation. For this mod something like dropping down number of scanning arrays a bit and adding hull parts to the satellites should balance things out.

**Comment by h2odragon** [comment]
Fixed with 1.7; reduced resource requirements a lot. I really appreciate yall chasing down the issue.
